added composio tools doc
phidatahq/phidata-docs pull request #47
Opened 2024-08-30 20:43 UTC by sohamganatra

2024-09-06 12:04 UTC, manthanguptaa requested changes

2024-09-09 21:10 UTC, sohamganatra commented on tools/composio.mdx
> +composio add github
Done. Thanks for pointing out.

2024-09-09 21:11 UTC, sohamganatra commented on tools/composio.mdx
> +composio_tools = toolset.get_actions(
We just deprecated get_actions in favour of get_tools. Have changed it to get_tools. Thanks for pointing out.

2024-09-10 08:28 UTC, manthanguptaa approved these changes

2024-09-10 08:54 UTC, merged