adding binary package , as it is required for running th rag script
phidatahq/phidata-docs pull request #5
Opened 2024-02-10 19:23 UTC by stkolanu

When i tried to follow the instruction, and run the script it mentioned me to have psycopg-binary package installed.
So, i tried adding it in the docs.
Let me know if its the right thing or not.
Getting to know things.

2024-02-10 19:35 UTC, ashpreetbedi commented
@stkolanu thank you and yes, absolutely the right thing to do. Quick change to replace `psycopg` with  `psycopg-binary` otherwise it will install psycopg first

2024-02-10 19:35 UTC, ashpreetbedi requested changes

2024-02-10 19:35 UTC, ashpreetbedi commented on basics.mdx
> +    pip install -U pgvector pypdf psycopg sqlalchemy psycopg-binary
@stkolanu thank you, i appreciate your contribution so much. Please replace `psycopg` with `psycopg-binary`.

Also please update the windows instructions on line 288.

Thank you again.

2024-02-10 19:35 UTC, ashpreetbedi commented on basics.mdx
>      ```bash Windows
@stkolanu please replace `psycopg` with `psycopg-binary` here as well.

2024-02-10 19:36 UTC, ashpreetbedi commented
@stkolanu mentioned you here: https://discord.com/channels/965734768803192842/965734768803192845/1205960434843127849

2024-02-11 17:59 UTC, ashpreetbedi approved these changes

2024-02-11 19:02 UTC, stkolanu commented
How to merge this PR?

2024-02-11 19:07 UTC, merged

2024-02-11 19:07 UTC, ashpreetbedi commented
Just merged :) thank you for contributing