🚧 WIP :: Embedding Docs
phidatahq/phidata-docs pull request #92
Opened 2024-11-13 11:18 UTC by Ansub

2024-11-20 11:15 UTC, manthanguptaa commented
Make the examples used consistent with the cookbook
https://github.com/phidatahq/phidata/tree/main/cookbook/embedders

2024-11-20 11:16 UTC, manthanguptaa requested changes
Make the examples used consistent with the cookbook
https://github.com/phidatahq/phidata/tree/main/cookbook/embedders

2024-11-21 07:40 UTC, Ansub commented
> Make the examples used consistent with the cookbook https://github.com/phidatahq/phidata/tree/main/cookbook/embedders

using examples from this PR, since it's changed:
https://github.com/phidatahq/phidata/pull/1473

2024-11-27 05:09 UTC, ysolanky approved these changes

2024-11-27 15:06 UTC, merged